---
name: Python Black Check
# https://github.com/rodrigogiraoserrao/python-black-check

on:
  push:
    paths:
      - "**.py"
      - "**.pyc"
      - "**.pyd"
      - "**.pyo"
  pull_request:
    paths:
      - "**.py"
      - "**.pyc"
      - "**.pyd"
      - "**.pyo"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  python-black-check:
    name: Python Black Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Python Black
        uses: rodrigogiraoserrao/python-black-check@v3.0
        with:
          # Ignore virtualenvs and non-source files
          exclude: "(venv|\\.venv|/*.html|/*.mo|/*.po|/*.png|/*.rst|/*.tf|/*.bash|/*.sh)"