name: Python Secrets POC

on:
  workflow_dispatch:

jobs:
  test-repo-secrets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run python script (repo secrets)
        env:
          API_KEY: ${{ secrets.API_KEY }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          python .github/workflows/secrets_test.py
